# Generated by Django 3.1.4 on 2020-12-19 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_model', models.CharField(max_length=150, null=True)),
                ('product_description', models.TextField(blank=True)),
                ('product_dimension', models.TextField(blank=True)),
                ('product_color_finish', models.TextField(blank=True)),
                ('product_material', models.TextField(blank=True)),
                ('product_image', models.ImageField(upload_to='product/')),
                ('price', models.PositiveIntegerField(null=True)),
                ('discount_price', models.PositiveIntegerField(null=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
